# Blog settings
permalink: bondstreetresearch.github.io


# My variables
name: Bond Street Research
description:   Bond Street Research provides discreet and confidential research 
  on issues of import. We specialize in fast recovery, slow release 
  data collection and employ a broad range of industry experts to 
  ensure tertiary strategy and insight for our global clientele.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
