title: Bond Street Research
description: >
  Bond Street Research provides discreet and confidential research 
  on issues of import. We specialize in fast recovery, slow release 
  data collection and employ a broad range of industry experts to 
  ensure tertiary strategy and insight for our global clientele.
url: bondstreetresearch.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
